training:    
    auto_lr: false
    learning_rate: 0.1
    scheduler: True
    wd : 0.0002
    moment: 0.8 
    batch_size: 19
    n_epochs: 50
    benchmark: True
    num_classes: 2 

    
model_config:
  model: 'FCN'
  pretrained: False
  eval_angle: False
  aji: False # Aji metric Evaluation during training


data_augmentation: 
  rotate: False
  scale: True
  size_img: 256
  size_crop: 240
  angle_max: 360 # Max angle for the random rotations

loader_gpu:
  nw: 4 # Num workers
  pm: True # Pin memory
  gpu: 2 # Device to use 


dataset: 
  split: True
  split_ratio: 0.1                   # Percentage of supervised data 
  dataroot_monuseg: '/share/DEEPLEARNING/datasets/monuseg'
  entire_image: True                 # Eval on the complete image 1000x1000 size
  target_size: '256'                 # arget size used for spliting images
  stride: '128'                      #Stride used for spliting images


save_config: 
  model_name: 'fully_supervised_monuseg'
  save_dir: '/share/homes/karmimy/equiv/save_model/fully_supervised_monuseg'
  save_all_ep: True
  save_best: False                     # If true will only save the best epoch model
